version: '3'
services:
  api_gateway:
    build:
      context: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - inference_service

  inference_service:
    build:
      context: ./inference_service
    ports:
      - "8001:8000"